### ISSUE TITLE
列表/網格 問題

### ISSUE THREAD

**Issue by EMK2000** [PureDark/H-Viewer#10]
如果我添加了多於一個站點，假設我把一個站點設定為網格。這時候如果我切換到第二個站點，然後再換回第一個站點，設定則會換回列表，需要重新轉換到網格。

另外，不知為甚麼 G.E-hentai 總是提示網絡錯誤，但是我本身就在牆外啊。

**Comment by PureDark** [comment]
因为控件的问题，现在切换之后是不会记住上次的选择的、所以的确是每次切换站点都会变成列表。

g.e之前测试还没问题，你一说我刚才去试了一下，发现确实刷不出来了，也不知道为什么……

**Comment by PureDark** [comment]
已经更新了，g.e和ex都支持了，可以正常显示了，并且还支持按分类浏览

**Comment by EMK2000** [comment]
厲害厲害
