### ISSUE TITLE
关于一些问题和一些建议

### ISSUE THREAD

**Issue by 1608637229** [PureDark/H-Viewer#11]
首先让我吐槽下这图标，也太暴力了，这样迟早是药丸呀！然后我用了几分钟，逛了逛n站，几分钟fc了两次，我猜恐怕你限制图片缓存上限的原因，看了几部本子就达到上限了，然后就fc，系统是cm13！然后是一些建议，能否考虑加些正常的插件，比如汗汗漫画(这个貌似也有点黄)，看漫画，cc图库之类的，虽然喜欢本子，但是正常的漫画也会看看的，或许可以考虑预装一两个正常的插件！最后，这个网站也不错，推荐一下  www.177pic66.com，有大神能做成插件就最好了！

**Comment by 1608637229** [comment]
刚刚又发现一些问题，下载好之后，具体是n站，只下了一部不知道是不是个例，下到最后只剩一张时迟迟下不动了，此时点击又不能看已经下好的，还有就是下完之后，我点进去看，看到一半以后，后面图片忽然全黑了，但是我这是下好了的啊，只能退出软件重进才能读出图片来。。这是什么bug呢

**Comment by PureDark** [comment]
会fc不是图片缓存的问题，可能是规则存在一些问题，下个版本会有大变动，虽然旧规则也兼容不会有问题，不过还是建议把现有的删掉重新扫所有规则，之前的有一些问题确实容易导致获取不到正确的图片

正规图站现在正在拓展中，下个版本就能支持pixiv了

下载的话最后一张迟迟不动有可能是因为IP被图站限制了，也可能是只有最后一张的服务器被墙了，特别是像ehentai这种图片是分布式储存的，可能某几个图片服务器没墙可以直接获取，某几个就被墙，这样看图时表现为只有某几张就是刷不出来，下载时就表现为就有几张一直失败

下载后必须退出重进才能看我这还没发生过……难排查

**Comment by PureDark** [comment]
我近期可能着重于功能更新，先不写新站点、
你贡献的这个站点很不错，希望有其他人看到来写一个规则吧

**Comment by 1608637229** [comment]
试了试最新的0.26版本，依然存在这个问题，在线阅读漫画，具体只测试了n站，每次到最后四五张图就加载不出来！黑屏，一直转圈！试了好几次了，都一样！还有当图片特别大的时候，滑动总给我一种有点掉帧的感觉，作者有没有考虑优化下在线阅读的体验，打开一个本子，目录全是预览图，如果以后有了正常的插件，有没有考虑目录是章节目录呢，总不可能几十话全都是预览图吧？？

**Comment by PureDark** [comment]
是小米刷的CM13吗，我这几天收到的报告里80%的OOM都是小米机型……

**Comment by 1608637229** [comment]
差不多，红米note3全高，

**Comment by PureDark** [comment]
看来小米的内存管理机制跟其他机型不大一样，你可以看看closed issues里还有另一个说经常OOM的，最后发现是小米内存管理的问题

我看看之后可能会换到Fresco来加载图片，应该能减少所有机型的OOM，但是不知道怎么针对小米优化

**Comment by manhong2112** [comment]
要是說看到最後幾張黑屏, 我也有類似情況, 然後也是小米.....

**Comment by 1608637229** [comment]
小米有毒，明明都刷了cm了

**Comment by PureDark** [comment]
请测试一下新版，0.3.2 换成Fresco框架来加载图片，应该能有效减少OOM，如果没有问题了给我反馈一下我就close掉这个issue

**Comment by 1608637229** [comment]
测试了，看到一半报错！

**Comment by PureDark** [comment]
看到了，看完报告我只有一个建议：换手机……

所有图片加载工作都交给Fresco之后，红米Note3仍然能OOM…… 而且Stack trace里完全没有涉及到我写的部分，全部都是在Fresco正常加载图片的时候OOM的

**Comment by 1608637229** [comment]
好吧，手里还得用一段时间，才买了一个月，以后不买小米了。。

**Comment by PureDark** [comment]
@1608637229 
Java Heap是java虚拟机给每个应用分配的内存的大小，机型不同设定的大小也不一样，我估计是不能通过刷系统解决的

一般这种图片应用有七八十mb大概能保证大多数情况不OOM

查了下资料，小米5的heap size是256mb，谷歌亲儿子n6p的heap size是288mb……

红米note3的heap size是……36mb……

**Comment by 1608637229** [comment]
感觉应该不是这个问题，我这个rom默认的是512m，刚刚特意看了

**Comment by PureDark** [comment]
512mb基本上就不可能OOM了，你下个AIDA64检查一下吧

**Comment by manhong2112** [comment]
剛剛OOM了幾次，啥都別說了，我需要靜靜。。手機才買了一年啊。。。

**Comment by PureDark** [comment]
我做的测试不够，OOM这么多，我怀疑有内存泄漏问题，我得用AS的monitor工具检测一下

**Comment by PureDark** [comment]
@manhong2112 @1608637229  
多亏了你们的反馈，我详细用AS的内存测试工具测试了一晚上，终于找到了两处内存泄漏的地方，然后修正后详细测试结果是，不管再浏览多少张图片，内存占用也不会超过100mb了

待会就推送v0.3.3

**Comment by PureDark** [comment]
@1608637229 顺便把177漫画的规则写了，更新在首页，之后再反馈下还有没有OOM的现象……

**Comment by manhong2112** [comment]
23點時出現了一次OOM，然後看大圖依然時不時有圖片沒出來(全黑)

**Comment by PureDark** [comment]
还有OOM的话我就不知道了，我本地测试一直修复内存泄漏的BUG后不管浏览多少图，内存占用都很稳定

不过看图是不是有一两张出不来是正常的，有两种可能，一种是没有获取到图片的地址，因为类似于e-hentai是需要逐页面访问才能获取到每一张大图的地址的，就跟用浏览器浏览一样，一次开五六个页面有时会访问失败，这个只要你往后刷一点然后再回来就会重新试图加载，或者退到目录重新点开，已经获得地址的图片会直接加载

第二种情况是，已经获取到图片地址，但是仍然加载失败，那就是那个图片服务器被墙了，因为像ehentai的图片都是分布式储存的，有一部分图片服务器可以直接访问到，有一部分图片服务器连接不成功，就算用浏览器看这几张图也加载不出来的

**Comment by manhong2112** [comment]
回到目錄再回來可以看到，不過流量沒怎變，不像是下載失敗重試的樣子，而且好像十張左右就會出現一次。。。不管從哪看起都一樣

**Comment by 1608637229** [comment]
我的已经没问题了，随便看了几个都没问题了

**Comment by yamabu** [comment]
泄漏可以用leakcanary测测

**Comment by yamabu** [comment]
ex的封面加载不出来的样子，fresco的okhttp的client的问题？

**Comment by PureDark** [comment]
@yamabu   
看来应该是了，ex的封面图没cookie在浏览器中也读不出来，因为图片服务器域名还是ex-hentai

点进去以后的缩略图和大图因为都是分布式储存的，host全是IP就没有检验是否登录的措施，所以还是只有封面图加载不出来

我检查一下为什么加载图片时cookie没有加到header里

**Comment by yamabu** [comment]
一个小问题，多次点击更新按钮会多次弹窗

**Comment by yamabu** [comment]
另一个建议，图片列表的缩略图大小是有可以显示大缩略图的，我忘了是不是账号需要hath买这个权限，虽然我可以自己改一下规则哈哈

**Comment by PureDark** [comment]
检查更新确实是会点几次检查几次，下次更新加上判断吧

图片列表的缩略图是要兼容不同站点的，还要兼容不同用户，而且缩略图本身就只需要起到一个能大概知道图片内容的作用就够了，具体其实小一点还能节省流量
