### ISSUE TITLE
還是網絡錯誤？

### ISSUE THREAD

**Issue by EMK2000** [PureDark/H-Viewer#12]
我更新後刪除了所有站點，重新加入。但是 G.E-hentai 仍然顯示網絡錯誤，甚麼也顯示不了。

另外，如果某個站點設置了網格顯示，但是退出應用，再重新開啟應用，默認又會變回列表了。

**Comment by PureDark** [comment]
即使新版中修正了一g.e规则中的一些问题，但是仍然是需要代理才能访问的，直接访问因为g.e被墙了所以还是会获取失败

网格和列表显示是不进行记录的，想使用列表就用列表，想使用 网格就使用网格，但是仅限当次使用

**Comment by EMK2000** [comment]
今日在 Play Store 才更新了 0.2.1，打開應用就叫我更新 0.2.2…但是 Play Store 好像還未有。

你的應用可以檢查並且下載更新，這樣子不是不能上架 Play Store 的嗎？

**Comment by EMK2000** [comment]
給個建議：希望可以增加一個“在瀏覽器打開”或者“分享”之類的選項，例如pixiv，有時候希望可以看看同一作者其他作品。

**Comment by PureDark** [comment]
get√
之后在点开item的目录页的右下角菜单里加一个在浏览器浏览
