### ISSUE TITLE
紳士漫畫 改版 封面又無法看了...求解

### ISSUE THREAD

**Issue by york74111** [PureDark/H-Viewer#120]
{
    "categories": [
        {
            "cid": 1,
            "title": "首页",
            "url": "https://wnacg.org/albums-index-page-{page:1}.html"
        },
        {
            "cid": 2,
            "title": "同人志",
            "url": "https://wnacg.org/albums-index-page-{page:1}-cate-5.html"
        },
        {
            "cid": 3,
            "title": "同人志-\u003e汉化",
            "url": "https://wnacg.org/albums-index-page-{page:1}-cate-1.html"
        },
        {
            "cid": 4,
            "title": "同人志-\u003e日语",
            "url": "https://wnacg.org/albums-index-page-{page:1}-cate-12.html"
        },
        {
            "cid": 5,
            "title": "同人志-\u003eCG画集",
            "url": "https://wnacg.org/albums-index-page-{page:1}-cate-2.html"
        },
        {
            "cid": 6,
            "title": "同人志-\u003eCosplay",
            "url": "https://wnacg.org/albums-index-page-{page:1}-cate-3.html"
        },
        {
            "cid": 7,
            "title": "单行本",
            "url": "https://wnacg.org/albums-index-page-{page:1}-cate-6.html"
        },
        {
            "cid": 8,
            "title": "单行本-\u003e汉化",
            "url": "https://wnacg.org/albums-index-page-{page:1}-cate-9.html"
        },
        {
            "cid": 9,
            "title": "单行本-\u003e日语",
            "url": "https://wnacg.org/albums-index-page-{page:1}-cate-13.html"
        },
        {
            "cid": 10,
            "title": "杂志",
            "url": "https://wnacg.org/albums-index-page-{page:1}-cate-7.html"
        },
        {
            "cid": 11,
            "title": "杂志-\u003e单篇汉化",
            "url": "https://wnacg.org/albums-index-page-{page:1}-cate-10.html"
        },
        {
            "cid": 12,
            "title": "杂志-\u003e日语",
            "url": "https://wnacg.org/albums-index-page-{page:1}-cate-14.html"
        }
    ],
    "disableHProxy": false,
    "extraRule": {
        "pictureRule": {
            "url": {
                "fun": "attr",
                "param": "src",
                "selector": "img#picarea"
            }
        }
    },
    "flag": "singlePageBigPicture|noRating|noTag|waterfallAsList|waterfallAsGrid",
    "galleryRule": {
        "description": {
            "fun": "html",
            "selector": "div.uwconn \u003e p:last-child"
        },
        "pictureRule": {
            "item": {
                "selector": "div.gallary_wrap ul li.gallary_item div.pic_box"
            },
            "thumbnail": {
                "fun": "attr",
                "param": "data-original",
                "selector": "a img"
            },
            "url": {
                "fun": "attr",
                "param": "href",
                "selector": "a"
            }
        }
    },
    "galleryUrl": "https://wnacg.org/photos-index-page-{page:1}-aid-{idCode:}.html",
    "gid": 3,
    "index": 0,
    "indexRule": {
        "cover": {
            "fun": "attr",
            "param": "data-original",
            "selector": "div.pic_box a img"
        },
        "datetime": {
            "fun": "html",
            "regex": "(\\d{4}-\\d{2}-\\d{2})",
            "selector": "div.info div.info_col"
        },
        "idCode": {
            "fun": "attr",
            "param": "href",
            "regex": "aid-(\\d+)",
            "selector": "div.pic_box a"
        },
        "item": {
            "selector": "div.gallary_wrap ul li.gallary_item"
        },
        "title": {
            "fun": "html",
            "selector": "div.info div.title a"
        }
    },
    "indexUrl": "https://wnacg.org/albums-index-page-{page:1}.html",
    "isGrid": false,
    "loginUrl": "https://wnacg.org/users-login.html",
    "searchUrl": "https://wnacg.org/albums-index-page-{page:1}-sname-{keyword:}.html",
    "sid": 59,
    "title": "绅士漫画"
}

有用版主的原文碼，目前封面圖又改掉了，無法正常看到封面。求高人指點改法

**Comment by PureDark** [comment]
直接在市场里更新规则就能获取到了

**Comment by york74111** [comment]
我市場裡获取到的，無法顯示圖片

PureDark <notifications@github.com> 於 2021年1月22日 週五 下午11:18寫道：
