### ISSUE TITLE
nhentai的规则坏了

### ISSUE THREAD

**Issue by greyglass** [PureDark/H-Viewer#131]
后缀.net改成.to能显示下载图片，但是tag的正则失效了，也不能用tag搜索，希望哪个大佬能改一下。

**Comment by kofal2012** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zx87662** [comment]
确实不行了

**Comment by PureDark** [comment]
更

**Comment by kofal2012** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
