### ISSUE TITLE
全面屏手势呼出分类菜单问题

### ISSUE THREAD

**Issue by tyjavajar** [PureDark/H-Viewer#138]
现在屏幕右侧向左滑 呼出分类菜单和全面屏手势返回冲突了，不能呼出分类菜单

**Comment by kofal2012** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by tyjavajar** [comment]
找到方法了，如果站点有多个分类，可以向左滑动或者长按屏幕右侧即可调出分类抽屉，选择其他分类可以切换页面。
