### ISSUE TITLE
建议图片加载控件用Fresco

### ISSUE THREAD

**Issue by ipercy** [PureDark/H-Viewer#15]
弃用Glide使用Fresco，OOM的问题会降到最低，图片加载流程也会大幅改善

**Comment by PureDark** [comment]
嗯，我的S7E测试了很久从来没OOM过，出现OOM的机器大都是5.0一下的，我去用虚拟机测试一下能不能复现OOM，先看看是不是有一些地方没释放对bitmap的引用导致gc没法回收

最后再考虑换成Fresco，Fresco确实是有挺多很强大的特性，但是毕竟一个框架用着要改也挺麻烦的，而且Glide作为google推荐的库应该不至于太差

**Comment by ipercy** [comment]
你用那么好的机子去测当然不会OOM了，因为5.0以上对内存管理改进很大，即使图片放到堆内存也没事。我Fork了你的项目，打算有时间换成Fresco试试。

**Comment by PureDark** [comment]
我详细看过并尝试过了，Fresco有一个硬伤，不支持每个请求独立加Header，这样没有办法加cookie和referer

**Comment by ipercy** [comment]
加cookie那不是okhttp的事吗，Fresco只负责下载管理图片，难道你要在下载图片时加cookie？

**Comment by PureDark** [comment]
是的，每个请求必须有独立指定的cookie和header，因为不同站点有不同cookie，不同图片有不同referer，一般的站点可以没有referer，但是比如pixiv这类加了防盗链的站，没有referer是下不到图片的

**Comment by ipercy** [comment]
对对对，防盗链的图片确实要这样，不过Fresco是支持自定义网络加载的，扩展性很好

**Comment by PureDark** [comment]
正像我所说的，虽然确实是可以拓展OkHttpNetworkFetcher，或者我只需要给okhttpclient调用addInterceptor加一个拦截器就能给请求加header，但是问题还是——没法独立给每个不同请求分别加不同个header，因为不管是指定NetworkFetcher还是加Interceptor，都是全局指定一次，没有办法在加载图片时传递header参数进去，我也不能每次发起一个请求就重新初始化一个新的OkHttpClient

目前我也还在想办法，因为Fresco使用native heap确实应该能大大缓解OOM

我继续往全局变量传参的思路思考一下

**Comment by ipercy** [comment]
哈哈，思路超好，我就知道难不倒你的

**Comment by ipercy** [comment]
刚打开就收到0.3.0的更新，看到已经改为Fresco框架了，效率要不要这么高，哈哈。更新后打开无限重启，然后一刷新就0.3.1了，可以可以

**Comment by PureDark** [comment]
因为改用Fresco变化比较大，才跳了几个版本号直接到0.3.0，但是之前测试时是直接编译到机子上运行的，生成release版时遵照Fresco的建议用了Proguard减少体积……结果收到好多错误报告啊，果然混淆的话没测试过还是先别启用了

现在更了0.3.2了，再修正了一个错误，之后应该基本上很少会有崩溃了，因为从0.2.6开始报告频率已经非常低了
