### ISSUE TITLE
更新規則

### ISSUE THREAD

**Issue by EMK2000** [PureDark/H-Viewer#16]
看到你說更新了 ExHentai 的規則，打算更新一下。
打開應用，長按站點，選編輯，然後點右上角的左邊的按鈕，打算貼上新複製的規則，但是不知為甚麼並不能選擇…

**Comment by PureDark** [comment]
那里做的其实是分享，并不能这样全面替换已存在站点，删掉重新扫吧

**Comment by EMK2000** [comment]
另一個建議，可不可以增加“對站點列表改變次序”的功能，而不是只可以“新增的在上面”

**Comment by PureDark** [comment]
@EMK2000 
加上了，估计是近期最后一次更新新功能了

**Comment by EMK2000** [comment]
更新了。非常感謝。

老實說，雖然不是經常用，但是從來沒有崩潰過，都不知你為甚麼收這麼多崩潰報告XD

**Comment by EMK2000** [comment]
不過，為甚麼更新規則後，EX-hentai 仍然看不到封面圖片，點進某漫畫則沒有問題，全部圖片也能看到。但是在目錄頁/首頁則加載不到圖片。

**Comment by PureDark** [comment]
崩溃是因为只有某类特定顺序的操作会引发崩溃，这类操作一般我自己也弄不出来，但是有报告的话我就能定位到具体的原因，比如一个有几百P的本子，目录页每页40P，在获取目录时需要一页一页获取，如果刚点开目录就直接进入浏览的话，会看到下面的数字是1/40，如果翻页一下会一下变成2/80之类的，这时就是因为还在不停刷新目录获取更多图片
但是如果这时还没加载完直接从浏览页退出、就会崩，这个一般我发现不了、但是有报告很快就修好了

Ex的封面光靠更新了规则没法获取到，我为了能获取到ex的规则还提到了更新了登录的机制啊，登录之后按右上角的√，访问一次首页，才能获取到完整的cookie，不然封面显示不了
