### ISSUE TITLE
推荐个安卓软件《mbooru》，作者可以参考一下

### ISSUE THREAD

**Issue by zhihaofans** [PureDark/H-Viewer#17]
# [酷安下载地址](http://www.coolapk.com/apk/com.sin3hz.android.mbooru)

### 介绍：这款Mbooru图库可以统一管理多个booru图站，也可以添加自定义图站，UI漂亮，非常好用。寒冬将至！

你可以参考一下

**Comment by PureDark** [comment]
有一些类似，但是还是不一样
没有啥地方可以参考的啊

排列图片时使用瀑布流，只适用于纯图站，而漫画站所有图都是一个比例的，需要方正的排列才适合阅读

**Comment by Futa2** [comment]
HI,i come from china，Your software is pretty good.

**Comment by PureDark** [comment]
@Futa2 
If so, then why are you speaking English? Isn't it a bit wierd to speak English to someone who is also Chinese like youself?

**Comment by Futa2** [comment]
这不是外网吗?

**Comment by PureDark** [comment]
@Futa2 
外网不代表不能用中文啊，又不是给其他人看的，交流对象之间用最容易交流的语言就行了

**Comment by Futa2** [comment]
Σ(°Д°;
