### ISSUE TITLE
懵逼

### ISSUE THREAD

**Issue by VoidForge** [PureDark/H-Viewer#18]
選擇器是什麼鬼啊，截取正則式是什麼鬼啊，替換式是什麼鬼啊，現在紳士要學編程了嗎？

**Comment by woorst9** [comment]
- -右上扫码

**Comment by PureDark** [comment]
请仔细研读首页README
这些是给有意写新站规则的人测试用，还有小幅度编辑站点用的。
一般的用户只需要扫写好的规则就行了
