### ISSUE TITLE
Flag 的可扩展性问题

### ISSUE THREAD

**Issue by wspl** [PureDark/H-Viewer#19]
目前存在 `noCover` `noRating` `noTag` 对于后续更新存在一些影响

例如将来想要加一个 阅读数 的设定，如果再添加一个叫做 `noViews` 的 flag，将会导致大部分规则里凭空多了个无用的 view 条目。

但是如果使用 `hasViews` 作为 flag，会和前面的那些 no**\* 产生混乱，导致写规则的时候会搞不清楚到底默认会显示哪些信息。

所以这个 issues 是提议将规则内 flag 全部替换成 has**\* 形式的。但是要做这个替换将会导致到部分用到 flags 的规则出现问题，所以需要一个合适的兼容方案。

欢迎讨论。

**Comment by wspl** [comment]
这里提供第一个方案：
对于 Collection 列表 Item 展示内容调整相关的 Flag 同时支持 `has***` 与 `no***`，这样就要求 flags 中不能同时存在 `has` 与 `no` 项。若存在 `has` 则默认全部隐藏，若存在 `no` 则默认全部显示。这样还是会产生冗余的无信息内容，所以需要联系到第二种方案。

第二个方案：
若不存在对于 Collection 列表 Item 展示内容调整相关的 Flag 时，将通过程序自动判断是否存在相关 selector 以进行显示。此时可以解决上面冗余信息内容的问题，即没有相关 selector，即使在 `no` 模式下不隐藏某个条目，都不会展示该没有数据源的内容。

**Comment by PureDark** [comment]
瞎鸡巴扯淡，没人觉得你提议靠谱，那会让根本就不需要用flag的网站也必须加flag才能达成最基本的展示效果#(滑稽)

但是讲道理本来大部分站就根本用不着flag
