### ISSUE TITLE
请大大加个萌妹网或者kanachan

### ISSUE THREAD

**Issue by 1520264471** [PureDark/H-Viewer#20]
地址是yande.re

**Comment by wspl** [comment]
与添加站点相关的请求请在 [https://github.com/H-Viewer-Sites/Apply/issues](https://github.com/H-Viewer-Sites/Apply/issues) 提交，谢谢合作。

**Comment by PureDark** [comment]
@wspl 
要求不要太高，很多人还是用手机看的github，要他们在一个不熟悉的网站找到正确的位置没必要
在这里发也可以的，既然这个站点没有写，那就应该保持open

**Comment by PureDark** [comment]
已经加了，看看： 
[站点列表](https://github.com/H-Viewer-Sites/Index/blob/master/HIDDEN.md)
