### ISSUE TITLE
求大大加个新h站点吧~~

### ISSUE THREAD

**Issue by Mrsquirrels** [PureDark/H-Viewer#21]
地址是nijiero-ch点com

**Comment by wspl** [comment]
为了规范 issues 功能以及方便维护人员回答问题，与添加站点相关的请求请在 [https://github.com/H-Viewer-Sites/Apply/issues](https://github.com/H-Viewer-Sites/Apply/issues) 提交，谢谢合作。

**Comment by PureDark** [comment]
@wspl 
要求不要太高，很多人还是用手机看的github，要他们在一个不熟悉的网站找到正确的位置没必要
在这里发也可以的，既然这个站点没有写，那就应该保持open

**Comment by PureDark** [comment]
已经加了，看看： 
[站点列表](https://github.com/H-Viewer-Sites/Index/blob/master/HIDDEN.md)
