### ISSUE TITLE
表示不是很懂新站点添加设置

### ISSUE THREAD

**Issue by yatounoneko** [PureDark/H-Viewer#22]
唯一看的懂的就是主页添加和搜寻页
下面那部分没有例子不是很懂。
如果可以，，，，
可否弄个例子，有例子的话我们就可以自己添加了，也可以省的你麻烦

另外那个Pixiv的站点添加后无法获取任何图片！！！
另外那个Pixiv的站点添加后无法获取任何图片！！！
另外那个Pixiv的站点添加后无法获取任何图片！！！

不过在这之前，可否顺便.....
添加下这些站点呗？
以下属于ACG类动漫站
Lolibooru：
https://lolibooru.moe/

Zerochan：
www.zerochan.net

Anime-pictures：
https://anime-pictures.net/

Konachan：
http://konachan.net/

Yande：
https://yande.re/

Sankaku complex：
https://chan.sankakucomplex.com/

**Comment by PureDark** [comment]
wiki最上面就是以实例为展开进行讲解的啊，不过那个教程不是面向普通用户的，至少要对HTML和jQuery有一定了解的程序员才能写新的站点

目前普通用户只要点进项目首页的查看所有站点的链接，添加已有站点就行了

**Comment by manhong2112** [comment]
我表示對第一個站點很感興趣XD儘管我現在愛莫能助
話係Pixiv那個。。你有登錄嗎。。

**Comment by EMK2000** [comment]
P站和EX也需要登錄才可以加載圖片。

**Comment by wspl** [comment]
添加站点有两种途径，一种就是直接添加别人已经写好的规则，另一种就是自己写规则。自己写规则的话需要基础的 HTML / CSS 知识，至少要会写 CSS 选择器以及基本的正则。所以零基础的话还是提交站点请求让有能力的人帮忙添加吧。（目前项目维护者都挺忙的，所以还是要靠整个开源社区去丰富站点的资源）

另：为了规范 issues 功能以及方便维护人员回答问题，与添加站点相关的请求请在 [https://github.com/H-Viewer-Sites/Apply/issues](https://github.com/H-Viewer-Sites/Apply/issues) 提交，谢谢合作。

**Comment by PureDark** [comment]
已经加了，看看： 
[站点列表](https://github.com/H-Viewer-Sites/Index/blob/master/HIDDEN.md)

因为主要先支持的是booru站，所以目前新写的有 Lolibooru 、Konachan和yande

其他几个站点之后看看有时间就写，或者有其他程序员愿意写的吗
