### ISSUE TITLE
可否解决下Android6.0下的相册无法正常显示图片的问题

### ISSUE THREAD

**Issue by yatounoneko** [PureDark/H-Viewer#23]
下载之后可以在软件中查看很不错的设计
但是想保存图片做个壁纸发给人什么的，在相册中却无法及时显示。
只能在文件查看器里边查看
似乎是没有获取权限还是什么的，我看别的看图软件能在相册显示的都要获取读取存储权限？
使用手机：
Samsung Galaxy Note7
系统：Android6.0.1

**Comment by PureDark** [comment]
嗯，因为大多数下载的是本子，所以默认是隐藏的，不在相册中显示的，如果想单独发一张图片给别人，可以在大图浏览时长按，然后单独把这张图片保存到另一个位置，然后就能正常在相册中找到了
