### ISSUE TITLE
次序變更

### ISSUE THREAD

**Issue by EMK2000** [PureDark/H-Viewer#26]
更新之後，原有的拖動改變次序不見了。

希望可以改變資料夾/站點的次序，甚至把一個資料夾的站點拖動到另一個資料夾，而不需要重新添加。

**Comment by PureDark** [comment]
并没有不见，仍然可以拖动排序的……

不过因为一些坐标上的判定问题，需要点图标稍微靠左一点的地方

**Comment by EMK2000** [comment]
早知這樣，我就不用重新添加所有站點了T.T

**Comment by EMK2000** [comment]
給個建議：
1. P 站如果可以，希望增加 R18 每日/每月排行榜
2. P 站如果可以，希望增加 LoveLive 標籤。3 大邪教不能缺這個。
3. 希望 9 以上繼續是 10、11、… 而不是全部 9+，不然 booru 系列還是不夠XD

**Comment by PureDark** [comment]
嘛，这些其实要是想加，完全可以自己编辑站点，依样画葫芦增加几个分类，把地址粘贴进去改一改page参数的位置

之后有时间我会直接更到站点规则里

**Comment by EMK2000** [comment]
好的，我試試自己研究一下

**Comment by PureDark** [comment]
另外9往上是9+是因为图标就那么多，图标不是我画的，是google的Material Icon库里有的，就只有1-9和9+，再往上我也没办法，9+其实也没太大影响吧，应该是够了的，大不了再把booru站分类细一点，比如post和pool分开存到不同组里
