### ISSUE TITLE
Any plan to add tinted status bar for 4.4 using KitKat translucent modes

### ISSUE THREAD

**Issue by WanderMax** [PureDark/H-Viewer#27]
However I have tablet in MM, but for my phone using KK, I just want to know is it supported or planed?
Thanks.

**Comment by PureDark** [comment]
well, I initially start this project with only a KK phone, and to make the app looks pretty was my top concern.
Of course it supports translucent status bar in 4.4.
The gifs in README.md are outdated, and because of the troubles to remake them, I kindda just leave them be.
