### ISSUE TITLE
規則更新的問題。。

### ISSUE THREAD

**Issue by manhong2112** [PureDark/H-Viewer#28]
能加一個更新規則的功能嗎。。。比如重掃QR Code，用json覆蓋，甚至是規則內部放一個更新的url之類的

**Comment by PureDark** [comment]
我看现在编辑站点里的复制json分享和生成二维码分享则没什么人用……毕竟要面对面分享站点的情景几乎没有啊，看来我还是把那两个改成和添加站点界面一样的功能吧

**Comment by PureDark** [comment]
已经可以用站内市场来更新了 ，这个issue就可以close 掉了吧

**Comment by manhong2112** [comment]
於是乎, 那兩個按鈕功能不變, 測試時還是得要新增一大堆XDDDD

**Comment by PureDark** [comment]
啊，对，你是想写新站点啊，那用扫码的方式测试确实挺麻烦的
其实我是想写个网页版的测试工具，粘贴规则和填入测试网址，就能测试得出最终获取的数据、以此判断到底取没取到值

等等吧、

**Comment by PureDark** [comment]
@manhong2112 正好我自己也需要用到，就连夜赶制了一个测试工具出来部署到heroku上了，你试试
https://hviewer.herokuapp.com/index.html
https://hviewer.herokuapp.com/gallery.html
第一个是测试获取列表的，第二个是测试点开后获取详情的
第一个粘贴站点规则后只需要填用这个规则解析的页面URL，可以用不同地址来测试首页和各个分类、搜索页是否都能成功获取，，只会获取第一页作为测试

第二个是粘贴站点规则后，把第一个站点测试获取到的随便哪个item粘贴进去，就能测试获取这个item的详情，同样只会获取第一页

**Comment by manhong2112** [comment]
哇X。。一覺醒來，連測試工具都寫好了。。。我放學後去試試看吧。。。

**Comment by manhong2112** [comment]
稍微試了下, 好像沒顯示pictureThumbnail和pictureUrl?
