### ISSUE TITLE
有關android 5之後的外接SD card路徑選擇

### ISSUE THREAD

**Issue by sm7428290** [PureDark/H-Viewer#29]
作者你好:

android 5之後的版本第三方app要存取外接儲存裝置時需要透過內建檔案瀏覽器利用document tree的方式來指定路徑，因此希望作者能更新支援android 5之後版本的下載資料夾外接儲存裝置路徑選擇，或是直接讓使用者可以key in資料夾路徑，第一張圖是H viewer的使用截圖，其他張則是另一可指定外接SD card的應用程式截圖

謝謝

![1](https://cloud.githubusercontent.com/assets/22043370/18806120/8ddf814e-8253-11e6-8e53-dc9a380fcbfe.png)
![2](https://cloud.githubusercontent.com/assets/22043370/18806121/8de199d4-8253-11e6-983a-3ca47a3df48e.png)
![3](https://cloud.githubusercontent.com/assets/22043370/18806123/8de2f964-8253-11e6-9a45-8c5946684d6d.png)
![4](https://cloud.githubusercontent.com/assets/22043370/18806122/8de2c0fc-8253-11e6-989e-84ca74abfe47.png)

**Comment by PureDark** [comment]
好的，下个版本5.0以上用OPEN_DOCUMENT_TREE intent来调用系统浏览器获取路径

**Comment by PureDark** [comment]
新版本已经全部采用Document API来进行路径读取、文件读取和文件写入操作了
