### ISSUE TITLE
关于缓存

### ISSUE THREAD

**Issue by gypick** [PureDark/H-Viewer#31]
1、缓存问题：能够加一个程序退出或关闭时自动清理图片缓存的功能？或者手动清理也可以。现在似乎并没有这个功能
2、排序问题：在左侧分类栏滑动的时候很容易误操作拖动项目，能否默认无法拖动排序，点击某个按钮或长按时间稍长才可以拖动

**Comment by PureDark** [comment]
如果关闭就自动清除缓存，那缓存的意义就没有了、
不过手动清理的选项可以放一个在设置里

**Comment by PureDark** [comment]
已经在设置中增加了缓存相关选项
