### ISSUE TITLE
求添加站点~谢谢 老司机

### ISSUE THREAD

**Issue by guoqiang2589** [PureDark/H-Viewer#33]
http://momoniji.com/ 桃色虹画像 -二次元萌え画像エロ画像まとめ
http://okkisokuho.com/ エロ画像まとめ おっき速報
http://egv.cc/ 二次エロ画像ビューア
http://charaud.com/ きゃらうど！ | アニメやゲームの美少女キャラのエロ画像を集めています。
http://nijinchu.com/ にじんちゅ -二次元エロ画像-
http://moeshunga.com/ 萌春画/二次元フルカラーエロ同人誌・漫画
........有点多 随意添加一俩个也行 谢谢啦

**Comment by PureDark** [comment]
其实加站点不难，开浏览器开发者工具调试大概10分钟一个站、
看什么时候有点空余零散时间就加吧

**Comment by IzualYang** [comment]
或者长期开个issue大家贴上自己的站点规则？
