### ISSUE TITLE
貢獻站點...?

### ISSUE THREAD

**Issue by manhong2112** [PureDark/H-Viewer#34]
依然沒支緩多圖...搞不太懂extraRule怎用, 嗯
新增站點時填json右下的叉叉點不到...
搜索時title中的關鍵字會被html tag包住...我是懶得想辦法了, 嗯
jsNeeded的flag加了也抓不到圖片, 我直接用regex在js中抽出來了...

    {
      "cookie": "",
      "flag": "preloadGallery",
      "galleryRule": {
        "datetime": {
          "fun": "html",
          "regex": "(.*).|",
          "selector": "div.timeIcon > div"
        },
        "description": {
          "fun": "html",
          "selector": "div.desc"
        },
        "item": {
          "selector": "body"
        },
        "pictureThumbnail": {
          "fun": "html",
          "regex": "s_url.*drawyoo(.*?)\"",
          "replacement": "http://i0.hdslb.com/bfs/drawyoo$1",
          "selector": "div.d_body > script"
        },
        "pictureUrl": {
          "fun": "html",
          "regex": "m_url.*drawyoo(.*?)\"",
          "replacement": "http://i0.hdslb.com/bfs/drawyoo$1",
          "selector": "div.d_body > script"
        },
        "rating": {
          "fun": "html",
          "regex": "(.*)/",
          "replacement": "$1/2",
          "selector": "div.rate_avg_num_f"
        },
        "tags": {
          "fun": "html",
          "selector": "div.p_tags > div.pic_tip div.tip_name"
        }
      },
      "galleryUrl": "http://h.bilibili.com/dy{idCode:}",
      "indexRule": {
        "cover": {
          "fun": "attr",
          "param": "src",
          "selector": "div > a > img"
        },
        "idCode": {
          "fun": "attr",
          "param": "href",
          "regex": "/dy(\\d*)",
          "selector": "div > a"
        },
        "item": {
          "selector": "ul.content_list > li.main_img"
        },
        "title": {
          "fun": "html",
          "selector": "div > a > div"
        },
        "uploader": {
          "fun": "html",
          "selector": "div > div.img_author_name"
        }
      },
      "indexUrl": "http://h.bilibili.com/list?page={page:1}",
      "loginUrl": "https://passport.bilibili.com/login",
      "picUrlSelector": {
        "fun": "attr",
        "param": "src",
        "selector": "img#pic"
      },
      "searchRule": {
        "cover": {
          "fun": "attr",
          "param": "src",
          "selector": "a.cover > img"
        },
        "idCode": {
          "fun": "attr",
          "param": "href",
          "regex": "/dy(\\d*)",
          "selector": "a.cover"
        },
        "item": {
          "selector": "div.ajax-render > li.draw-item"
        },
        "title": {
          "fun": "html",
          "selector": "a.headline"
        },
        "uploader": {
          "fun": "html",
          "selector": "div.up-name"
        }
      },
      "searchUrl": "http://search.bilibili.com/drawyoo?keyword={keyword:}&page={page:1}",
      "title": "Bilibili 画友"
    }

**Comment by PureDark** [comment]
extraRule是根据flag不同有不同含义的

如果加了secondLevelGallery，那么extraRule就可以看成是一个galleryRule，第一层galleryRule获取到的Picture的URL看成是extraRule要获取的gallery的地址

另外jsNeededFlag只是确保执行一次页面的js，但是没法处理那些需要互动才能生效的JS，比如需要鼠标放上去才会把地址填进去的图片之类的、

现在的这个规则应该是可以用的没问题、我之后给你放上市场，你有空可以研究下怎么支持多图

**Comment by PureDark** [comment]
accepted

**Comment by manhong2112** [comment]
改一下galleryRule的pictureUrl, 這是抓原圖的, 不過要登錄才能用...

        "pictureUrl": {
          "fun": "html",
          "regex": "\"(\\d*)\",\"s_url[\\S\\s]*list_id = (\\d*)",
          "replacement": "http://h.bilibili.com/dy$2/$1",
          "selector": "div.d_body > script"
        }

**Comment by PureDark** [comment]
其实我已经改了一部分了，不过抓原图这个可以拿来改造一下。
