### ISSUE TITLE
在线测试地址出现500错误

### ISSUE THREAD

**Issue by zhihaofans** [PureDark/H-Viewer#35]
https://hviewer.herokuapp.com/gallery.html
返回结果一直都是"[object Object]",用FireBug一看是“500 Server Error"

**Comment by PureDark** [comment]
也许你没填对应画册的数据，也许粘贴的画册数据多了个逗号，总之是之类的错误

因为我用你写的那个规则测试过了，可以获取到（只是返回的数据中没有图片，这个我已经给你改好了）

**Comment by zhihaofans** [comment]
我用bilibili画册测试就返回"java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $"...

**Comment by PureDark** [comment]
你是直接把整个列表都粘贴进去了吧……

要测试获取详情只能粘贴一个item啊，不能在图册数据的输入框里把整个数组都填进去的
