### ISSUE TITLE
关于右侧拉出分类显示的建议

### ISSUE THREAD

**Issue by zhihaofans** [PureDark/H-Viewer#36]
建议可以像其他MD风格的安卓软件(如ehviewer)一样从屏幕中间开始拉出而不是只能从屏幕右侧边缘开始拉出，现在拉出分类显示需要2只手拿手机很不方便。
而且分类列表的各行建议能增加一下高度和宽度(而不是根据字数来改变)
![273129410586572258.jpg](https://ooo.0o0.ooo/2016/10/18/58059a454a7f0.jpg)

**Comment by PureDark** [comment]
已加单手模式，打开则可以接近屏幕中间的部分就拉出抽屉
