### ISSUE TITLE
apk  download url

### ISSUE THREAD

**Issue by LittleRobotRoad** [PureDark/H-Viewer#4]
(┬＿┬)

**Comment by IndeedPlusPlus** [comment]
We are actively fixing the automatic building system. The stable/daily builds will be available soon. Thank you for your patience.

**Comment by PureDark** [comment]
it's in the releases
check here
https://github.com/PureDark/H-Viewer/releases

**Comment by LittleRobotRoad** [comment]
谢谢，不太会用github，只会下载代码和checkout。没发现旁边就有releases
