### ISSUE TITLE
零域动漫壁纸

### ISSUE THREAD

**Issue by cuzfinal** [PureDark/H-Viewer#41]
{
    "disableHProxy": false,
    "extraRule": {
        "pictureRule": {}
    },
    "flag": "noRating|preloadGallery",
    "galleryRule": {
        "commentRule": {
            "author": {
                "fun": "html",
                "selector": "span[node-type='nickname'] a"
            },
            "avatar": {
                "fun": "attr",
                "param": "src",
                "selector": "div.cont-head-gw img"
            },
            "content": {
                "fun": "html",
                "selector": "div.cont-msg-gw p.issue-wrap-gw span"
            },
            "datetime": {
                "fun": "html",
                "selector": "div.cont-msg-gw span.user-time-gw"
            },
            "item": {
                "selector": "div[node-type='cmt-list'] div[node-type='cmt-item']"
            }
        },
        "pictureRule": {
            "item": {
                "selector": "article p a img"
            },
            "thumbnail": {
                "fun": "attr",
                "param": "data-original",
                "selector": "this"
            },
            "url": {
                "fun": "attr",
                "param": "data-original",
                "regex": "(http://.*/www.lingyu.me_\\d{17})",
                "replacement": "$1.jpg",
                "selector": "this"
            }
        },
        "tags": {
            "fun": "html",
            "selector": "footer div.single-tag a[rel='tag']"
        }
    },
    "galleryUrl": "http://www.lingyu.me/bizhi/{idCode:}/{page:1}",
    "gid": 1,
    "header": "",
    "index": 0,
    "indexRule": {
        "cover": {
            "fun": "attr",
            "param": "data-original",
            "selector": "figure div.f4 img"
        },
        "datetime": {
            "fun": "html",
            "regex": "(\\d{4}-\\d{1,2}-\\d{1,2})",
            "selector": "div.entry-content span.entry-meta span.date:nth-child(2)"
        },
        "idCode": {
            "fun": "attr",
            "param": "href",
            "regex": "bizhi/(.*)",
            "selector": "header a"
        },
        "item": {
            "selector": "article"
        },
        "title": {
            "fun": "html",
            "selector": "header h2 a"
        },
        "uploader": {
            "fun": "html",
            "selector": "span.entry-meta span.date a"
        }
    },
    "indexUrl": "http://www.lingyu.me/page/{page:1}",
    "isGrid": false,
    "loginUrl": "",
    "searchUrl": "http://www.lingyu.me/?s={keyword:}",
    "sid": 74,
    "title": "零域动漫壁纸",
    "versionCode": 0
}

**Comment by PureDark** [comment]
datetime的regex需要进行转义：
```javascript
"regex": "发布时间：(\\d{4}年\\d{2}月\\d{2}日)"
```

另外看了一下，你取到的地址是类似于   
`http://tp.lingyu.me/bz/uploads/2016/11/www.lingyu.me_20161125150528356-1024x716.jpg`    
原图地址是类似于   
`http://tp.lingyu.me/bz/uploads/2016/11/www.lingyu.me_20161125150528356.jpg`    
唯一的区别只是后面没有分辨率的部分，这样的话highRes完全可以先取到和url一样的内容，然后通过正则表达式来获得原图地址啊

**Comment by cuzfinal** [comment]
向正则表达势力低头

**Comment by PureDark** [comment]
就等你完善一下然后再加到市场里

如果你之后还有写其他站点的意愿，而不是写了一个就跑的话、、
那也可以在这里发一条issue: [H-Viewer-Sites/Apply](https://github.com/H-Viewer-Sites/Apply/issues)
申请这个组织的协作权，然后在H-Viewer-Sites下创建一个repo，具体可以参考 [zhihaofans](https://github.com/H-Viewer-Sites/zhihaofans)
建立自己的sites.json就可以自由添加自己的站点了

**Comment by cuzfinal** [comment]
已经可以获取大图了，我写一个就跑。

**Comment by PureDark** [comment]
OK，只写一个的话那我就手动修正然后收录吧、
还有点问题我替你改好了，顺便附上有兴趣的话可以参考。
```javascript
{
    "disableHProxy": false,
    "extraRule": {
        "pictureRule": {}
    },
    "flag": "noRating|preloadGallery",
    "galleryRule": {
        "commentRule": {
            "author": {
                "fun": "html",
                "selector": "span[node-type='nickname'] a"
            },
            "avatar": {
                "fun": "attr",
                "param": "src",
                "selector": "div.cont-head-gw img"
            },
            "content": {
                "fun": "html",
                "selector": "div.cont-msg-gw p.issue-wrap-gw span"
            },
            "datetime": {
                "fun": "html",
                "selector": "div.cont-msg-gw span.user-time-gw"
            },
            "item": {
                "selector": "div[node-type='cmt-list'] div[node-type='cmt-item']"
            }
        },
        "pictureRule": {
            "item": {
                "selector": ".entry-content a>img"
            },
            "thumbnail": {
                "regex": "\"([^\"]*\\.(?:jpg|jpeg|png|gif|bmp))\"",
                "selector": "this"
            },
            "url": {
                "regex": "\"([^\"]*\\.(?:jpg|jpeg|png|gif|bmp))\"",
                "selector": "this"
            },
            "highRes": {
                "regex": "\"([^\"]*)-[^\"]*?\\.(jpg|jpeg|png|gif|bmp)\"",
                "replacement": "$1.$2",
                "selector": "this"
            }
        },
        "tags": {
            "fun": "html",
            "selector": "footer div.single-tag a[rel='tag']"
        }
    },
    "galleryUrl": "http://www.lingyu.me/bizhi/{idCode:}/{page:1}",
    "gid": 1,
    "header": "",
    "index": 0,
    "indexRule": {
        "cover": {
            "fun": "attr",
            "param": "data-original",
            "selector": "figure div.f4 img"
        },
        "datetime": {
            "fun": "html",
            "regex": "(\\d{4}-\\d{1,2}-\\d{1,2})",
            "selector": "div.entry-content span.entry-meta span.date:nth-child(2)"
        },
        "idCode": {
            "fun": "attr",
            "param": "href",
            "regex": "bizhi/(.)",
            "selector": "header a"
        },
        "item": {
            "selector": "article"
        },
        "title": {
            "fun": "html",
            "selector": "header h2 a"
        },
        "uploader": {
            "fun": "html",
            "selector": "span.entry-meta span.date a"
        }
    },
    "indexUrl": "http://www.lingyu.me/page/{page:1}",
    "isGrid": false,
    "loginUrl": "",
    "searchUrl": "http://www.lingyu.me/?s={keyword:}",
    "sid": 74,
    "title": "零域动漫壁纸",
    "versionCode": 0
}
```
