### ISSUE TITLE
【长期征集】iOS 版本从开坑到有生之年

### ISSUE THREAD

**Issue by wspl** [PureDark/H-Viewer#46]
目前已决定使用的开发语言 Swift 4，???，将只适配 iOS 11 及以上版本，暂无 iPad 版本计划。速度切换至马拉松级别，现已加入有生之年系列套餐。

开发过程出生产了如下轮子：
- PLUi - 嵌套代码布局 DSL
- PLIcon - Iconfont 支持类
- PLLoad - Pull to refresh / Load more 插件

目前正在开发一种 MVVM DSL  -  Vi，支持双向绑定响应式数据流，嵌套式代码布局。

在这些轮子造完之前估计还是不会正式开始动工 iOS 版本。

**Comment by Ferouden** [comment]
icloud\Mega\DropBox 同步

**Comment by PureDark** [comment]
别展望了，这个傻逼已经完全放弃了#(滑稽)

**Comment by wspl** [comment]
都说了还没开始了，放弃个毛#(滑稽)

**Comment by bshumaster** [comment]
建议使用自适应布局（不了解 iOS 开发，大概叫这个。参考知乎客户端），这样不用单独适配也可以在 iPad 上全屏使用，而不是像一般的 iPhone 应用在 iPad 上一样的体验极其差劲的强行缩放的界面（参考 QQ iPhone 版在 iPad 上的效果）。

**Comment by wspl** [comment]
@bshumaster 打算 iPad 和 iPhone 分别做布局。。。不过 iPhone 版肯定优先发布啦，因为没有 iPad。。。。

**Comment by ricekiller** [comment]
IOS版真的能上appstore吗，还是像哔卡那样有隐藏模式？
话说有开放端口吗，安卓上以前用Muzei配合Mbooru就很好，能随时改壁纸就神了。

**Comment by wspl** [comment]
@ricekiller 肯定会上，默认不带任何站点和站点源，需要用户手动添加站点源

**Comment by spartawhy117** [comment]
居然是swift 3，如果是OC的话就还能帮一下忙，一些3d touch的开发我还比较熟悉

**Comment by lhj5426** [comment]
只支持IOS11 ？？？？等iPhone 8 之后的设备得了

**Comment by guider** [comment]
不错 准备参与开发  能否给个参与方式 除了PR 私到 guider@yeah.net

**Comment by guider** [comment]
希望可以参与  可以提供本人长期积累起的MVVM框架

**Comment by codexss** [comment]
https://github.com/DaidoujiChen/Dai-Hentai
https://github.com/kayanouriko/E-HentaiViewer

**Comment by pstkqzy** [comment]
我OC 和swift都能使用  如有可能我也希望能参与到项目中

**Comment by sn20110327** [comment]
正要从安卓跳阵营到iPhone 大概是少数没有合适替代品的软件了

**Comment by CodeSlaveZhang** [comment]
资深iOS程序猿，前快播iOS主程序猿在此报道。有需要可联系俺

**Comment by SergIo-21** [comment]
yealico  这个软件不错就是  内购太贵了

**Comment by PureDark** [comment]
> yealico 这个软件不错就是 内购太贵了

？？？内购？
这个软件完全免费不含任何内购，如果你下了一个带了内购的版本，就是其他人篡改用于牟利的版本，与我无关

**Comment by sn20110327** [comment]
他说的内购是指yealico 不是hviewer啦

**Comment by SergIo-21** [comment]
> 他说的内购是指yealico不是hviewer啦

是的   我说的是  yealico  ios 软件    不是说hviewer    开发者误会我意思了

**Comment by SergIo-21** [comment]
> > yealico这个软件不错就是内购太贵了
> 
> ???内购？
> 这个软件完全免费不含任何内购，如果你下了一个带了内购的版本，就是其他人篡改用于牟利的版本，与我无关

你误会我意思了，我说的是另外一个软件，yealico  ios版本的。

**Comment by PureDark** [comment]
> > > yealico这个软件不错就是内购太贵了
> > 
> > 
> > ???内购？
> > 这个软件完全免费不含任何内购，如果你下了一个带了内购的版本，就是其他人篡改用于牟利的版本，与我无关
> 
> 你误会我意思了，我说的是另外一个软件，yealico ios版本的。

了解，顺便这个issue该关了，某人已经完全放弃治疗了，根本没有任何填坑的打算 斜眼
