### ISSUE TITLE
不能在app上编辑规则

### ISSUE THREAD

**Issue by tangyuanfu** [PureDark/H-Viewer#49]
新建一个规则时首页规则以下的都不能正常保存。
设备:oneplusone cm13和chrome上的ARC Welder

**Comment by PureDark** [comment]
因为Selector增加了JsonPath的支持，而应用上实在是没地方放编辑框了，本意是直接禁止在应用上对首页规则以下部分进行编辑，但是设置了Editable为false后不知为何仍然可以编辑框内内容，虽然不能保存

下个版本我会把首页规则以下设为只能看不能改的，要测试新规则，务必参考wiki，使用网页版测试工具，一切测好再通过二维码扫描添加到应用上进行实际测试
