### ISSUE TITLE
ngx on npm

### ISSUE THREAD

**Issue by gdi2290** [PureDark/H-Viewer#5]
can I have `ngx` on npm so I can release ngx jsx like syntax for angular2

**Comment by IndeedPlusPlus** [comment]
Thank you for posting suggestion. However the current implementation does not involve any rendering of browser or Javascript execution. The rules based on raw html. We try to avoid complex Javascript based rule for the sake of simplicity.

P. S. Thank you for your contribution to the Javascript community.
