### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by MikiraSora** [PureDark/H-Viewer#50]
浏览界面希望能另外选择成类似于Mbooru那样仅有图的形式(以及长按出选项可以直接下载)，这样的话不仅能快速阅览，还能方便下载。找图党瞬间头顶青天

**Comment by PureDark** [comment]
现在不就有类似mbooru的浏览模式么，编辑站点，把列表模式或者九宫格模式替换成瀑布流就行了

不过长按直接下载没有做，下个版本看看加上吧
