### ISSUE TITLE
图片链接 base64

### ISSUE THREAD

**Issue by tangyuanfu** [PureDark/H-Viewer#52]
获取图片时，一部分正常，一部分获取的链接变成data:image/gif;base64,....(一长串字符),flag用jsNeededAll也一样,求大佬指教！！！

**Comment by PureDark** [comment]
data:image/* 这类开头的是，是直接把图片数据转成base64码直接放到html里了

我记得fresco应该也能识别的，直接取就行了，应用里应该能正常显示的

**Comment by tangyuanfu** [comment]
搞不定啊，图片显示不出来，有没有现成的站点借鉴一下

**Comment by PureDark** [comment]
这不全是么 
https://github.com/H-Viewer-Sites/Index/tree/master/sites

能转成base64存HTML里的一般都是小图啊，大图不会这么做的

**Comment by tangyuanfu** [comment]
明白了
