### ISSUE TITLE
Website add and some suggestions

### ISSUE THREAD

**Issue by zay448345045** [PureDark/H-Viewer#53]
I didn't know that developer also knows the website, doujinshi.org,some translation group may moved those comic/x to exh.It is excellent!!!
I will appreciated if can open h-viewer-sites/index's issues, it is helpful.Thanks to developer,I am truly grateful to your development for what you have done

**Comment by PureDark** [comment]
ok. I'll see to it when I have more free time.

and people were suppose to post issues to H-Viewer-Sites/Apply to request rule of new site, but now I realize that would be inconvenient . I have now opened Index's issues.
