### ISSUE TITLE
GBK编码网站中文乱码

### ISSUE THREAD

**Issue by ShallYu** [PureDark/H-Viewer#54]
这个软件真是超棒！！！
只是GBK和GB2312的网页识别出的title和文字内容会乱码。
比如西祠胡同。
This app is really super Korean!
but it seems not support GBK and GB2312.

**Comment by zhihaofans** [comment]
是哪个网站呢？如果是JSON的网站出现乱码的话，作者说下个版本修复

**Comment by ShallYu** [comment]
自己试着给西祠胡同（比如[http://www.xici.net/b1114902]）写的JSON，APP里全是菱形的乱码，用UTF8读GBK是会这样。

**Comment by zhihaofans** [comment]
这个是json的，编码是在response header里的，目前获取编码的方式只是从网页的` `<meta charset="***">`获取而已，所以json获取编码失败就直接utf-8了，作者说下个版本将会修复

**Comment by PureDark** [comment]
已修复，现在会优先从Response Header里取charset

**Comment by ShallYu** [comment]
摸摸大~
