### ISSUE TITLE
jquery获取到长度为1的数组怎么取数组元素啊😯，$()[]会自动变成$("[]")

### ISSUE THREAD

**Issue by tangyuanfu** [PureDark/H-Viewer#57]

**Comment by PureDark** [comment]
使用nth-child()等css伪类来指定元素，而不是先选出一个数组，再从数组中选指定元素

**Comment by tangyuanfu** [comment]
大佬，还是不会啊。(´╥ω╥`)整个页面只有一个video标签，$("video")却要$("video")+["0"]才能访问属性值

**Comment by PureDark** [comment]
不用……你直接写`$("video").attr("src")`之类的就行了……
规则也可以直接写
```json
"selector": "video",
"fun": "attr",
"param": "src"
```
