### ISSUE TITLE
请问方便不方便支持Muzei

### ISSUE THREAD

**Issue by Fireblossom** [PureDark/H-Viewer#58]
如题_(:з」∠)_想弄动态桌面壁纸

**Comment by PureDark** [comment]
Muzei并不是一个图片来源网站，它的图片也是通过其他站点得到的，而Muzei的各种壁纸相关功能本应用都不可能做到

如果是想设置动态壁纸，请继续用Muzei

**Comment by Fireblossom** [comment]
窝的意思是导出一个muzei的壁纸源_(xз」∠)_
怎么说呢。。。就和mbooru一样的，在右上角有一个添加到muzei的选项，就可以做动态壁纸源了

**Comment by Fireblossom** [comment]
本身是因为pixiv的相关URL改变了我不能更新壁纸了才找到的这里，不过pixiv-for-muzei昨天更新了蹦蹦跳跳，我对这个功能的需求不是那么迫切了~但还是希望能有啦~靴靴~

**Comment by PureDark** [comment]
pixiv……我看了一下，没啥问题啊？应用里应该还是可以正确获取到pixiv的所有图片相关地址的啊

你如果说的是这个应用和muzei的互动、那我没办法吧、除非muzei的接口注册的就是分享图片的那个，那你可以试试直接在图片上长按，选分享，然后选muzei

**Comment by Fireblossom** [comment]
对，我的意思就是H-Viewer和muzei的互动，比如说我喜欢pixiv的图，我就可以在H-Viewer里选择把pixiv添加到muzei的源，(大概)相当于H-Viewer给muzei每小时提供一张图片，mbooru是有这个功能，可惜那个没开源我也不清楚具体如何实现滴~如果我表述还不清楚的话，我想个办法给你截图(躺
