### ISSUE TITLE
提几个建议,贡献一个站.

### ISSUE THREAD

**Issue by vvyoko** [PureDark/H-Viewer#6]
1，希望有自定义UA选项，很多站点移动版限制很多而PC版几乎没有限制。
2，现在版本登录靠cookies实在是太麻烦了，分享规则不可能把自己的COOKIES分享出来不说，而且还不一定持久。希望有个内置壳浏览器，只用来登录就可以了。
3，现有版本的一些选项几乎无用，例如标签分类之类，如果可以希望支持跳转，几乎大部分网站标签和分类的模板和“首页”都是一样的。不用做重复工作。（如可行建议增加一个选项，因为毕竟还是有些网站模板不一样。）
4，首页有列表和网格，希望增加纯文字类型，很多站点首页并不一定有缩略图。

顺便请教一下图片URL和图片跳转URL分别是指什么？
图片跳转好像是大图？图片URL没弄明白。
另外类似/photo/1718/d.jpg这种地址好像不支持？

附上站点：（上面几个疑问没解决，只是能看的程度，大大看哪个地方不对可以改一下。）

`{
  "cookie": "",
  "galleryRule": {
    "item": {
      "selector": ".postimg.post p a"
    },
    "pictureThumbnail": {
      "fun": "attr",
      "param": "src",
      "selector": "img",
       "regex": "^(.*)$",
       "replacement": "http://www.rosiyy.com/usr/themes/mm/timthumb.php?src=$1&h=130&w=195&zc=1&q=100"
    },
    "pictureUrl": {
      "fun": "attr",
      "param": "src",
      "selector": "img",
      "regex": "^(.*)$",
      "replacement": "http://www.rosiyy.com/$1"
    }
  },
  "indexRule": {
    "cover": {
      "fun": "attr",
      "param": "src",
      "selector": ".photo>a>img"
    },
    "idCode": {
      "fun": "attr",
      "param": "href",
      "regex": "http://www\\.rosiyy\\.com/(.*)",
      "selector": ".photo>a"
    },
    "item": {
      "selector": "#content div.pic"
    },
    "title": {
      "fun": "html",
      "selector": ".entry_title a"
    }
  },
  "picUrlSelector": {
    "fun": "attr",
    "param": "src",
    "selector": "img"
  },
  "galleryUrl": "http://www.rosiyy.com/{idCode:}?page={page:1}",
  "indexUrl": "http://www.rosiyy.com/index-{page:1}.html",
  "searchUrl": "http://www.rosiyy.com/search/{keyword:}/list-{page:1}",
  "title": "Rosi"
}
`

**Comment by PureDark** [comment]
1.可以考虑，不过目前是使用okhttp获取的目标网址html，应该不会因为UA跳转为移动版吧
2.目前还不打算支持需要登录的站点，cookie这一项其实本来是不开放直接输入的，现在只是作为临时方案，以后会做成内置WebView可以手动登录并自动获取Cookie
3.标签和分类一些站点有一些站点没有，e-hentai和nhentai、wnacg都是有的，所以还是不可少，跳转不可行，因为如下面url的部分可见，要从一个网址获取数据，里面必须人工指定一些参数，比如page等，如果url是动态从网页上获取的，很难判别参数的位置，或者说很难写出兼容所有站点的判别方法
4.这个可以有，之前只是写纯图站的才写成这样，然后发现也支持1024这样的论坛时，就觉得其实可以给一个参数是否隐藏Cover

最后，你写的时候有参考过wiki么？
https://github.com/PureDark/H-Viewer/wiki/%E6%80%8E%E4%B9%88%E8%87%AA%E5%AE%9A%E4%B9%89%E6%96%B0%E7%9A%84%E7%AB%99%E7%82%B9%E8%A7%84%E5%88%99

虽然我知道我写得很烂，不是很通俗，基本上是逐属性解释，但是也能起到个字典的作用，哪个属性不是很理解就只看这个属性应该没问题

那么解释一下图片URL和图片跳转URL，galleryRule里的pictureUrl获取的是图片跳转地址没错
因为一般图站的结构是这样的

首页（很多item）——>图册详情（目录里很多张图片缩略图）——>大图浏览页

所以galleryRule->pictureUrl获取的是图片的跳转地址，galleryRule->pictureThumbnail获取的图片缩略图，这两个是成对的

而Site->picUrlSelector获取的是打开跳转地址后的网页中的大图的src

/photo/1718/d.jpg 这样的地址是支持的，wiki说明了支持绝对地址和相对地址

**Comment by vvyoko** [comment]
3的意思是部分页面模板其实和“首页”是一样的，所以不用再重新写了。
比方
https://nhentai.net/（首页）
https://nhentai.net/parody/touhou-project/ 
https://nhentai.net/artist/ahru/
这几个的模板其实是一样的，其实现在的搜索和首页应该是一个模板吧，这就是一个意思。
再列一个秀人的
http://www.xiuren.org/（首页）
http://www.xiuren.org/category/TuiGirl.html
http://www.xiuren.org/tag/%E5%AE%89%E9%9D%99.html
相当大一部分网站都是这样的。搜索和首页也应该是一个模板吧。
当然这样不能像前面那样获取文本了，相关页面得支持解析HTML。然后模板一致的可以直接提取整段标签，比方说NHENTAI可以直接提取.span.tags（得做好相对链接的处理）。甚至可以提取.section#tags(标签作者语言分类一次全提取了。)模板不一致的继续获取原来的那种就行了。这样CSS可能会有一点问题。不过还是能看的。

关于图片跳转URL和图片URL我就想问下picUrlSelector翻译成中文是哪个（滑稽）
图片URL在首页规则的上面，图片跳转URL在图片目录规则下面。
galleryRule->pictureUrl难道是翻译成了图片跳转URL？
我大概明白了相册里还能跳转一次，但是不知道哪个是跳转的参数~~~~而且这样跳转参数应该是可选吧，1024之类的不跳转也行啊。

相对地址的问题我也不清楚是怎么回事，比方说下面正则的作用只是把相对地址转成绝对地址。
如果不转直接就FC了。
{ "fun": "attr", "param": "src", "selector": "img", "regex": "^(.*)$", "replacement": "http://www.rosiyy.com/$1" } }, 
这个也是，按说提取的应该是绝对链接了但是^(.*)$获取的是/photo/1718/d.jpg这种相对链接。
 { "fun": "attr", "param": "src", "selector": "img", "regex": "^(.*)$", "replacement": "http://www.rosiyy.com/usr/themes/mm/timthumb.php?src=$1&h=130&w=195&zc=1&q=100" },

**Comment by PureDark** [comment]
其实现在想来，picUrlSelector应该改成picSrcSelector比较好的，不容易歧义，url代表跳转地址，src代表图片src，然而毕竟已经出了那么多个站了，现在想改也不好改了2333

分类我懂你的意思了，就是分类的网址点进去其实完全可以套用首页的模板来提取，不需要另写，这个之后我再考虑怎么在不大幅变动现有规则格式的前提下加进去

相对地址的话，处理的时候时，如果获取到的是相对地址，则自动按照获取到的源地址把地址补全

比如如果你在http://www.rosiyy.com/anonymous-model/rosi1718.html下，取到了/photo/1718/d.jpg，那么最后得到的是http://www.rosiyy.com/photo/1718/d.jpg

我看了一下你这个站，情景是从列表点开以后，直接就是大图，而没有再开一页一页查看的页面，这个情景和秀人网一样，我之前的一次更新已经做了支持了

对于列表就是大图的网站，只需要在pictureUrl和pictureThumbnail都取得图片src就行了，picUrlSelector不填，让它为null

**Comment by PureDark** [comment]
```javascript
{
    "cookie": "",
    "galleryRule": {
        "datetime": {
            "fun": "html",
            "regex": "发布时间：(\\d{4}年\\d{2}月\\d{2}日)",
            "selector": ".postimg.post"
        },
        "tags": {
            "fun": "html",
            "selector": ".postimg.post a[rel='tag']"
        },
        "item": {
            "selector": ".postimg.post p a"
        },
        "pictureThumbnail": {
            "fun": "attr",
            "param": "src",
            "selector": "img",
            "regex": "^(.*)$",
            "replacement": "http://www.rosiyy.com/usr/themes/mm/timthumb.php?src=$1&h=130&w=195&zc=1&q=100"
        },
        "pictureUrl": {
            "fun": "attr",
            "param": "src",
            "selector": "img"
        }
    },
    "indexRule": {
        "cover": {
            "fun": "attr",
            "param": "src",
            "selector": ".photo>a>img"
        },
        "idCode": {
            "fun": "attr",
            "param": "href",
            "regex": "http://www\\.rosiyy\\.com/(.*)",
            "selector": ".photo>a"
        },
        "item": {
            "selector": "#content div.pic"
        },
        "title": {
            "fun": "html",
            "selector": ".entry_title a"
        }
    },
    "galleryUrl": "http://www.rosiyy.com/{idCode:}?page={page:1}",
    "indexUrl": "http://www.rosiyy.com/index-{page:1}.html",
    "searchUrl": "http://www.rosiyy.com/search/{keyword:}/list-{page:1}",
    "title": "Rosi"
}
```

你看一下，我给你优化了一下，并加上了时间和标签获取，当然只有点开了才能获取到，列表还是没有

然后给你添加到首页的站点列表里、、

**Comment by PureDark** [comment]
现在已经更新了，支持登录和给站点定义多个分类，你要不要试试再写几个站？
