### ISSUE TITLE
Exhentai无法访问

### ISSUE THREAD

**Issue by no1xsyzy** [PureDark/H-Viewer#62]
重现步骤：
打开R18开关，添加exhentai并登录

期望结果：
能够正常访问exhentai内图集

实际结果：
全白

*****

实际上，在登录过程的最后，显示了一瞬间熊猫。
但是我这个账号电脑上exhentai是正常用的啊。

**Comment by PureDark** [comment]
无解，熊猫永远是帐号问题，且除了拿自己的帐号其他人没法复现
多试试登录几次。
