### ISSUE TITLE
gentai图站一直没有图

### ISSUE THREAD

**Issue by z747414964** [PureDark/H-Viewer#63]
已经重新登出登入 但是一直保持没有图的状态

**Comment by zhihaofans** [comment]
@z747414964 已修复，谢谢指出

 [commit f9b7f5c](https://github.com/H-Viewer-Sites/zhihaofans/commit/f9b7f5cc1475b9d854ad891e5e1161fcfbc874b1)

**Comment by zhihaofans** [comment]
已删除 `gentai-jp` ,变更线路请去个人账户设置里设置

 [commit 072709f](https://github.com/H-Viewer-Sites/zhihaofans/commit/072709f08bbec3ca4fe196fe763860dd25930642)
