### ISSUE TITLE
 二次萌エロ画像ブログ软件里搜索只显示十个，后面都不显示了

### ISSUE THREAD

**Issue by 1520264471** [PureDark/H-Viewer#66]
二次萌エロ画像ブログ软件里搜索只显示十个，后面都不显示了

**Comment by zhihaofans** [comment]
这个网站搜索没有翻页功能 [配置文件](https://github.com/H-Viewer-Sites/Index/blob/master/sites/%E4%BA%8C%E6%AC%A1%E8%90%8C%E3%82%A8%E3%83%AD%E7%94%BB%E5%83%8F%E3%83%96%E3%83%AD%E3%82%B0.txt#L103)

**Comment by PureDark** [comment]
忘记加分页参数了啊，加上了，更新规则就行了

虽然没空更新应用，更新个规则还是可以的

倒不如说这个站上次更新时间是去年9月了， 这么久居然没人发现问题啊
