### ISSUE TITLE
关于Hproxy如何配置？或者说是网络问题？

### ISSUE THREAD

**Issue by Sutton-G** [PureDark/H-Viewer#7]
好几个网站显示：网络错误，请重试

**Comment by PureDark** [comment]
因为被墙了，挂个VPN就能上了

HProxy需要有基本的服务器知识，并有处于国外的支持note.js的空间或VPS才能使用，之后如果有时间会出一个教怎么注册国外空间并把HProxy部署上去的教程

**Comment by Tubunu** [comment]
@PureDark 能支持XX-NET和GoProxy这类的GAE软件的局域网代理吗？

**Comment by PureDark** [comment]
支持不支持那得看代理本身啊
这个应用只会向对应URL请求html并解析，能不能获取到HTML完全看网络环境，如果你用的代理会自动拦截并转发请求，并把获取的结果返回，那就能用。

**Comment by wspl** [comment]
H-Proxy 目前还处于实验性阶段，对于如何部署也不打算推出教程，而是希望用户利用自己的现有知识去进行部署。目前可以提供的帮助就是 H-Proxy 的 Repo 可以直接 fork 然后用 heroku 一键部署。
