### ISSUE TITLE
【功能建议】希望可以將APP 當做瀏覽器設定 開啟, 

### ISSUE THREAD

**Issue by Garytang01** [PureDark/H-Viewer#78]
FACEBOOK 有時會POST 一些有關網站的 LINK  , 但是ANDROID 無法直接分享到H-VIEWER 開啟的,  只有CHROME / 瀏覧器的選擇,   希望可以加入 按LINK 就可直接用H-VIEWER 開啟的,   謝

**Comment by PureDark** [comment]
没有专门针对网站写的规则，是无法解析这个网站的图册的，这个应用不是通用浏览器啊
