### ISSUE TITLE
发现问题和几个建议

### ISSUE THREAD

**Issue by zhihaofans** [PureDark/H-Viewer#8]
问题:
1下载时整个软件很卡
2下载列表里长按会退回软件首页
建议：
1建议可以下载完成前也可以在下载列表打开浏览
2建议在下载目录加个".nomedia"文件，不然图片会满相册都是，因为相册软件会扫描到

暂时只有这么多，谢谢

**Comment by zhihaofans** [comment]
还有一个问题
在线浏览图时经常闪退到首页

**Comment by PureDark** [comment]
下载时会卡我这没有发现，不管是真机还是虚拟机都测试过，很奇怪，开了新线程应该不会影响UI线程
在下载的ITEM上长按应该是显示删除才对，怎么会崩溃退到首页呢？

建议的两点可以加上，特别是第二点应该是很必要的，下个版本就加上

**Comment by zhihaofans** [comment]
我昨晚又试了几次，发现不是软件问题是系统问题，miui的反人类内存管理机制的问题，其他软件也出现这样的问题

**Comment by PureDark** [comment]
现在下载时已经会自动加.nomedia文件了

下载中查看暂时还没闲暇做，因为忙着支持登录和站点多分类，更新了，看看吧
