### ISSUE TITLE
BUG?

### ISSUE THREAD

**Issue by reply7251** [PureDark/H-Viewer#83]
[Screenrecorder-2018-03-18-15-12-18-76.mp4.zip](https://github.com/PureDark/H-Viewer/files/1822446/Screenrecorder-2018-03-18-15-12-18-76.mp4.zip)

**Comment by PureDark** [comment]
这是这个网站的搜索就是这么设定的，超过页数的时候会重复显示最后一页的结果，你搜索的这个只有3页结果，所以超过第三页后会重复刷出第三页的结果。
