### ISSUE TITLE
幾個問題

### ISSUE THREAD

**Issue by manhong2112** [PureDark/H-Viewer#9]
嗯, 首先我正在弄pixiv, 但是圖片(原圖和縮略圖)的下載貌似需要在header加上referer才能夠下載, 所以能否加上修改header的規則?

另外就是, pixiv的列出最新作品需要登錄才能用, 首先就是我把document.cookie的內容複製貼上後也依然是讀取不了, 其次就是把登錄了的cookie公開好像不太安全?

還有, 這個和pixiv關係不大, searchUrl的選擇器好像和indexUrl共用indexRule? 這樣如果遇到index和search的不一樣的網站會不會就用不了了?

另外還希望有搜索tag的功能, 和rating在沒有rating時能夠隱藏起來

**Comment by manhong2112** [comment]
剛忘了, 還有按tag搜索的功能, 和rating在沒有給rating時依然會出現

**Comment by PureDark** [comment]
pixiv我当初试图写过规则，但是确实目前的规则形式不大兼容，我回头会想办法
支持登录这个功能会是下次更新的主要更新功能，不再需要手动输入cookie，分享时也不会把cookie带上
（对了应用内分享自己的站点还没做……）

index和search的这个……有道理，我之后给站点拓展个searchRule，如果在没有的情况下则采用indexRule，这样既不会影响已有的规则，在遇到搜索和首页的模板不一样的情况下也可以拓展

搜索tag的话，现在的搜索因为是统一的关键词搜索，所以能不能搜索tag其实是看网站的，比如lofi.e和g.e，只要在搜索中输入的关键字是某一个tag，基本上带有这个tag的内容都能搜索出来，目前因为要兼容所以不大可能专门做一个tag搜索

rating和cover的隐藏都在考虑中，这样也可以支持一些比如1024这样的论坛图贴，在列表中时把封面隐藏（因为本来也获取不到）

**Comment by manhong2112** [comment]
我是想, 有一些網站會檢查header或user agent, 如果可以修改header或ua, 就可以針對這個來偽裝, 比如pixiv我測試了下就算登錄了, 直接用url下載圖片會出403, 必須要referer是pixiv的網站才能拿到

tag搜索如果要兼容的話可以是個可選功能吧, 支援的話就能用, 否則就只有普通搜索這樣, 又或者tag過濾之類的, 只要網站有tag就能用這樣

另外就是pixiv有一次性投稿多張和18X, 兩個的規則和一般的不一樣.....我也是無力吐槽了...後者還可以再弄個規則, 畢竟有獨立的搜索之類的, 前者我是沒辦法了

剛想起b站也有圖站, 我去看看能不能做一個出來XD

**Comment by PureDark** [comment]
你有没有注意到一个现象，p站的图，搜索的页面出来的图会是这样一个url：
http://i2.pixiv.net/c/150x150/img-master/img/2016/08/24/14/20/12/58622265_p0_master1200.jpg

这个图确实只在有referer的情况下才能获取，我直接在新tab打开，然后刷新一下就会变成403
但是你试试把链接中的150x150改成240x480

http://i2.pixiv.net/c/240x480/img-master/img/2016/08/24/14/20/12/58622265_p0_master1200.jpg

你会发现居然可以获取了……

但是仅限240x480这个分辨率，要想要原图分辨率还是要加referer，我去设置一下任何图片请求都把获取到html的页面url作为referer吧

**Comment by manhong2112** [comment]
我還真沒發現...240x480這分辨率是用在甚麼地方了吧XD

另外b站的圖要登錄才有原圖...看來我等更新再做吧~XD

**Comment by manhong2112** [comment]
b站有多張圖時貌似沒辦法直接拿到每一張圖的id....第一張以外的圖是遞增的, 但第一張的id不能直接用selector拿到, 是放在js裡的...反正在有相關更新前我是放棄這方面了.....

另外, 不知道為甚麼點進去後的縮略圖出不來, 但我自己在galleryUrl那頁時用
`$("div.img_wrapper").find("a.img > img").attr("src")`
是可以拿到圖片網址的, 縮略圖應該也不需要referer或cookie的, 是哪裡出錯了嗎?
`{
  "cookie": "",

  "title": "Bilibili 画友",

  "indexUrl": "http://h.bilibili.com/list?page={page:1}",
  "searchUrl": "http://search.bilibili.com/drawyoo?keyword={keyword:}&page={page:1}",
  "galleryUrl": "http://h.bilibili.com/dy{idCode:}",
  "indexRule": {
    "item": {
      "selector": "ul.content_list > li.main_img"
    },
    "cover": {
      "fun": "attr",
      "param": "src",
      "selector": "div > a > img"
    },
    "idCode": {
      "fun": "attr",
      "param": "href",
      "regex": "/dy(\\d*)",
      "selector": "div > a"
    },
    "title": {
      "fun": "html",
      "selector": "div > a > div"
    },
    "uploader": {
      "fun": "html",
      "selector": "div > div.img_author_name"
    }
  },

  "galleryRule": {
    "item": {
      "selector": "div.img_wrapper"
    },
    "pictureThumbnail": {
      "fun": "attr",
      "param": "src",
      "selector": "a.img > img"
    },
    "pictureUrl": {
      "fun": "attr",
      "param": "href",
      "selector": "a.img"
    }
  },

  "picUrlSelector": {
    "fun": "attr",
    "param": "src",
    "selector": "img#pic"
  }
}`

**Comment by PureDark** [comment]
已经更新了，在站点上长按进行登录，登陆后会自动记录cookie，分享时不会带上cookie

你可以试写一下pixiv的规则了……

上面的规则我还没试过，不过jsoup虽然号称是支持jquery语法，但是内部实现不一定完全是按照jquery的方式，你试试少使用 > 来指定一级子元素，直接用空格来间隔看看

关于新规则的写法，我更新wiki还需要一点时间，你可以重点看一下ex-hentai的规则，大部分新特性都体现到了

**Comment by manhong2112** [comment]
嗯..如下, 除了評分不知為何用不了而關掉外能加的應該都加了
另外, 補幾個問題,
regex 格式有錯誤的話會直接崩潰(話說打錯了是不是其實應該怪我XD),
還有登錄後重打開app需要重新登錄(登錄頁面的狀態倒是保存着)

    {
      "title": "Pixiv",
      "loginUrl": "https://accounts.pixiv.net/login",
      "searchUrl": "http://www.pixiv.net/search.php?word={keyword:}&p={page:1}",
      "indexUrl": "http://www.pixiv.net/new_illust.php?p={page:1}",
      "flag": "noRating",
      "indexRule": {
        "item": {
          "selector": "ul._image-items > li.image-item"
        },
        "cover": {
          "fun": "attr",
          "param": "src",
          "selector": "a.work > div._layout-thumbnail > img._thumbnail"
        },
        "datetime": {
          "fun": "attr",
          "regex": ".*img/(\\d{4})/(\\d{2})/(\\d{2})/(\\d{2})/(\\d{2})/(\\d{2})",
          "replacement": "$1-$2-$3 $4:$5:$6",
          "selector": "a.work > div._layout-thumbnail > img._thumbnail",
          "param": "src"
        },
        "idCode": {
          "fun": "attr",
          "param": "href",
          "regex": ".*illust_id=(.*)",
          "replacement": "$1", 
          "selector": "a.work"
        },
        "title": {
          "fun": "html",
          "selector": "a > h1.title"
        },
        "uploader": {
          "fun": "html",
          "selector": "a.user"
        }
      },
      "galleryUrl": "http://www.pixiv.net/member_illust.php?mode=medium&illust_id={idCode:}",
      "galleryRule": {
        "item": {
          "selector": "body"
        },
        "title": {
          "fun": "html",
          "selector": "div.ui-expander-target > h1.title"
        },
        "uploader": {
          "fun": "html",
          "selector": "a.user-link > hi.user"
        },
        "datetime": {
          "fun": "html",
          "selector": "ul.meta > li:eq(0)"
        },
        "tags": {
          "fun": "html",
          "selector": "ul.tags > li.tag > a.text"
        },
        "rating": {
          "fun": "html",
          "selector": "section.score",
          "regex": ".*rated-count\">(\\d+).*score-count\">(\\d+).*",
          "replacement": "$2 / $1 / 2"
        },
        "pictureThumbnail": {
          "fun": "attr",
          "param": "src",
          "selector": "div.works_display > div > img"
        },
        "pictureUrl": {
          "fun": "attr",
          "param": "data-src",
          "selector": "img.original-image"
        }
      }
    }

**Comment by PureDark** [comment]
嗯，很多地方其实写代码的时候都是走happy path的，除非遇到了错误不然都不会写异常判断，遇到出错了才会在这段前面加一句检查的代码、

regex我之后也加上格式检测吧

**Comment by manhong2112** [comment]
多張投稿沒法在一般投稿的頁面選擇出來, 能選擇出來的網址不能在一般的投稿, 估計是沒辦法放在同一規則了

關於分類, 我後來有在categories加上18R的頁面XD, 但沒看出有甚麼分別, 就沒更新了, 是怎用的XDD

**Comment by PureDark** [comment]
categories里最好加入首页之后再加其他分类，不然切换以后没法返回首页

具体的使用方法是，在屏幕右侧向左滑动拉出分类菜单……

**Comment by manhong2112** [comment]
加了一堆奇奇怪怪的分類..

剛剛貌似因為json格式錯誤發了兩次log
然後app卡在..呃..站點頁面? 讀不出圖片列表, 但抓包看了看網絡貌似是沒問題的...
        {
          "title": "Pixiv",
          "loginUrl": "https://accounts.pixiv.net/login",
          "searchUrl": "http://www.pixiv.net/search.php?word={keyword:}&p={page:1}",
          "indexUrl": "http://www.pixiv.net/new_illust.php?p={page:1}",
          "flag": "noRating",
          "categories": [
            {
              "cid": 1,
              "title": "Index",
              "url": "http://www.pixiv.net/new_illust.php?p={page:1}"
            },
            {
              "cid": 2,
              "title": "18R",
              "url": "http://www.pixiv.net/new_illust_r18.php?p={page:1}"
            },
            {
              "cid": 3,
              "title": "10000users入り",
              "url": "http://www.pixiv.net/search.php?s_mode=s_tag&word=10000users%E5%85%A5%E3%82%8A&p={page:1}"
            },
            {
              "cid": 4,
              "title": "5000users入り",
              "url": "http://www.pixiv.net/search.php?s_mode=s_tag&word=5000users%E5%85%A5%E3%82%8A&p={page:1}"
            },
            {
              "cid": 5,
              "title": "3000users入り",
              "url": "http://www.pixiv.net/search.php?s_mode=s_tag&word=5000users%E5%85%A5%E3%82%8A&p={page:1}"
            },
            {
              "cid": 6,
              "title": "1000users入り",
              "url": "http://www.pixiv.net/search.php?s_mode=s_tag&word=5000users%E5%85%A5%E3%82%8A&p={page:1}"
            },
            {
              "cid": 7,
              "title": "Loli",
              "url": "http://www.pixiv.net/search.php?s_mode=s_tag_full&word=%E3%83%AD%E3%83%AA&p={page:1}"
            },
            {
              "cid": 8,
              "title": "東方",
              "url": "http://www.pixiv.net/search.php?s_mode=s_tag_full&word=%E6%9D%B1%E6%96%B9&p={page:1}"
            },
            {
              "cid": 9,
              "title": "艦これ",
              "url": "http://www.pixiv.net/search.php?s_mode=s_tag_full&word=%E8%89%A6%E3%81%93%E3%82%8C&p={page:1}"
            },
            {
              "cid": 10,
              "title": "VOCALOID",
              "url": "http://www.pixiv.net/search.php?s_mode=s_tag_full&word=VOCALOID&p={page:1}"
            }
          ],
          "indexRule": {
            "item": {
              "selector": "ul._image-items > li.image-item"
            },
            "cover": {
              "fun": "attr",
              "param": "src",
              "selector": "a.work > div._layout-thumbnail > img._thumbnail"
            },
            "datetime": {
              "fun": "attr",
              "regex": ".*img/(\\d{4})/(\\d{2})/(\\d{2})/(\\d{2})/(\\d{2})/(\\d{2})",
              "replacement": "$1-$2-$3 $4:$5:$6",
              "selector": "a.work > div._layout-thumbnail > img._thumbnail",
              "param": "src"
            },
            "idCode": {
              "fun": "attr",
              "param": "href",
              "regex": ".*illust_id=(.*)",
              "replacement": "$1",
              "selector": "a.work"
            },
            "title": {
              "fun": "html",
              "selector": "a > h1.title"
            },
            "uploader": {
              "fun": "html",
              "selector": "a.user"
            }
          },
          "galleryUrl": "http://www.pixiv.net/member_illust.php?mode=medium&illust_id={idCode:}",
          "galleryRule": {
            "item": {
              "selector": "body"
            },
            "title": {
              "fun": "html",
              "selector": "div.ui-expander-target > h1.title"
            },
            "uploader": {
              "fun": "html",
              "selector": "a.user-link > hi.user"
            },
            "datetime": {
              "fun": "html",
              "selector": "ul.meta > li:eq(0)"
            },
            "tags": {
              "fun": "html",
              "selector": "ul.tags > li.tag > a.text"
            },
            "rating": {
              "fun": "html",
              "selector": "section.score",
              "regex": ".*rated-count\">(\\d+).*score-count\">(\\d+).*",
              "replacement": "$2 / $1 / 2"
            },
            "pictureThumbnail": {
              "fun": "attr",
              "param": "src",
              "selector": "div.works_display div._layout-thumbnail > img"
            },
            "pictureUrl": {
              "fun": "attr",
              "param": "data-src",
              "selector": "img.original-image"
            }
          }
        }

**Comment by PureDark** [comment]
很不错，不过提示一点，如果regex只有一个组的情况下，会自动采用，不需要再加 "replacement": "$1" ，这样在处理的时候会多一次替换操作，降低效率，不过倒也不是什么很严重的问题、

**Comment by manhong2112** [comment]
會拿不到有多張投稿的圖片，原本想直接用正規替換，起碼能拿到一張，然而因為有jpg和png兩種副檔名，又拿不到正確的副檔名，以失敗告終XD

**Comment by PureDark** [comment]
我更新了，进行对内部实现进行了魔改，加了一个flag强行支持了pixiv这种同时存在一图和多图两种不同浏览逻辑的情况……

你可以扫一下现在的pixiv的规则看看……

**Comment by manhong2112** [comment]
試了! 隨便挑了幾張都可以, 就是大圖和下載時不是原圖有點可惜

**Comment by PureDark** [comment]
多图的是原图、单图的我忘记改了，可以通过正则把中间的分辨率部分改成1200x1200，然后就基本都是原图了

我之后更新一下规则，把单图时的缩略图替换成150x150，大图替换成1200x1200
现在多图就是这么做的

**Comment by manhong2112** [comment]
嗯, 也只能這樣子了, 我自己加個pid顯示然後用電腦下載就好XD

**Comment by PureDark** [comment]
确实，其实不用纠结我设定的uploader、category的含义，这只影响显示的位置，比如要是没有category，那用category选中pid并显示也是不错的

**Comment by manhong2112** [comment]
我是打算在title那邊加上的, 不過加在category好像也不錯, 反正也是空着, 另外cookie在離開app後依然會不見, 要重新進去登錄頁面...

**Comment by PureDark** [comment]
登录之后编辑站点，应该可以看到cookie栏填入了内容
然后马上退出再打开，再编辑站点看看，cookie还有吗？
我之前测试时是有的……
话说应该是0.2.6吧？

**Comment by manhong2112** [comment]
進編輯後按返回, cookie會消失, 但按那個FAB就不會, 是0.2.6沒錯

**Comment by PureDark** [comment]
之前编辑站点之后不会保存，已修正，这个issue可以关掉了吧

**Comment by manhong2112** [comment]
雖然不是甚麼大問題，站點列表上方可以點到後面的圖片等等，除此之外應該沒了

**Comment by PureDark** [comment]
说起来bilibili 画友你要不要完善一下，我再给加到站点里

**Comment by manhong2112** [comment]
最近用不了電腦啊(傷心)
