### ISSUE TITLE
177站点出现问题

### ISSUE THREAD

**Issue by jayjames2000** [PureDark/H-Viewer#97]
无法载入图片

**Comment by weironx** [comment]
长按编辑，所有配置url的地方前缀改为http://www.177picaa.info
原因估计是网站域名换了

**Comment by ksqb0137793** [comment]
> 长按编辑，所有配置url的地方前缀改为http://www.177picaa.info
> 原因估计是网站域名换了

谢谢大佬！

**Comment by waterbao** [comment]
好像又换了域名，最新的要改成什么样的？

**Comment by sunbeams001** [comment]
http://www.177pic001.info/

**Comment by PureDark** [comment]
修好了
